import {
  Stethoscope,
  HeartPulse,
  Heart,
  Baby,
  PersonStanding,
  Bone,
  Brain,
  Syringe,
  Pill,
  PillBottle,
  Thermometer,
  Activity,
  Eye,
  Glasses,
  Ear,
  Wind,
  Droplet,
  Droplets,
  Bug,
  Scissors,
  Waves,
  Shield,
  ShieldPlus,
  User,
  Users,
  AlertTriangle,
  Microscope,
  TestTube,
  TestTubes,
  Cross,
  Hospital,
  Ambulance,
  Bandage,
  Dna,
  FlaskConical,
  ClipboardList,
  ClipboardPlus,
  Zap,
  ZapOff,
  Moon,
  Sun,
  Flame,
  Skull,
  Radiation,
  Biohazard,
  Bed,
  BedDouble,
  Clock,
  Timer,
  Utensils,
  Apple,
  Cigarette,
  Wine,
  Milk,
  Salad,
  Footprints,
  Dumbbell,
  Accessibility,
  Smile,
  Frown,
  Meh,
  BrainCog,
  Venus,
  Mars,
  VenusAndMars,
  Flower2,
  Leaf,
  Sparkles,
  Star,
  CircleAlert,
  Siren,
  LifeBuoy,
  HandHeart,
  Scan,
  ScanLine,
  Radius,
  Waypoints,
  Filter,
  Beaker,
  Tablets,
  Wheat,
  WheatOff,
  Fish,
  EyeOff,
  Ribbon,
  ShieldAlert,
  ShieldCheck,
  Stars,
  MoonStar,
  CloudRain,
  Snowflake,
  ThermometerSun,
  ThermometerSnowflake,
  HeartCrack,
  BicepsFlexed,
  type LucideIcon,
} from 'lucide-react'

export const ICONES: Record<string, LucideIcon> = {
  Stethoscope,
  HeartPulse,
  Heart,
  Baby,
  PersonStanding,
  Bone,
  Brain,
  Syringe,
  Pill,
  PillBottle,
  Thermometer,
  Activity,
  Eye,
  Glasses,
  Ear,
  Wind,
  Droplet,
  Droplets,
  Bug,
  Scissors,
  Waves,
  Shield,
  ShieldPlus,
  User,
  Users,
  AlertTriangle,
  Microscope,
  TestTube,
  TestTubes,
  Cross,
  Hospital,
  Ambulance,
  Bandage,
  Dna,
  FlaskConical,
  ClipboardList,
  ClipboardPlus,
  Zap,
  ZapOff,
  Moon,
  Sun,
  Flame,
  Skull,
  Radiation,
  Biohazard,
  Bed,
  BedDouble,
  Clock,
  Timer,
  Utensils,
  Apple,
  Cigarette,
  Wine,
  Milk,
  Salad,
  Footprints,
  Dumbbell,
  Accessibility,
  Smile,
  Frown,
  Meh,
  BrainCog,
  Venus,
  Mars,
  VenusAndMars,
  Flower2,
  Leaf,
  Sparkles,
  Star,
  CircleAlert,
  Siren,
  LifeBuoy,
  HandHeart,
  Scan,
  ScanLine,
  Radius,
  Waypoints,
  Filter,
  Beaker,
  Tablets,
  Wheat,
  WheatOff,
  Fish,
  EyeOff,
  Ribbon,
  ShieldAlert,
  ShieldCheck,
  Stars,
  MoonStar,
  CloudRain,
  Snowflake,
  ThermometerSun,
  ThermometerSnowflake,
  HeartCrack,
  BicepsFlexed,
}

export function IconePorNome({ nome, className }: { nome: string | null | undefined; className?: string }) {
  const Comp = (nome && ICONES[nome]) || ClipboardList
  return <Comp className={className} />
}

export function IconPicker({
  valor,
  onChange,
}: {
  valor: string | null
  onChange: (nome: string) => void
}) {
  return (
    <div className="grid grid-cols-8 gap-1.5 p-2 bg-surface-2 border border-border rounded-md max-h-56 overflow-y-auto">
      {Object.entries(ICONES).map(([nome, Icone]) => (
        <button
          key={nome}
          type="button"
          title={nome}
          onClick={() => onChange(nome)}
          className={`flex items-center justify-center aspect-square rounded-md border transition-colors ${
            valor === nome
              ? 'border-accent bg-accent/15 text-accent'
              : 'border-transparent text-text-dim hover:text-text hover:bg-surface'
          }`}
        >
          <Icone className="w-4 h-4" />
        </button>
      ))}
    </div>
  )
}
